name: Automate Merges to Customer X Branch

on:
  pull_request:
    branches:
      - customerX
  push:
    branches:
      - main

jobs:
  merge_customerX:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge requests from main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git fetch origin customerX
          git branch -la
          git checkout customerX
          # Merge branch-to-merge with the --no-commit option to prevent automatic commit
          git merge main --no-commit --allow-unrelated-histories
          # Resolve conflicts by always taking the version from branch-to-merge
          git ls-files -u | awk '{print $4}' | while read conflicted_file
          do
              git checkout --theirs "$conflicted_file"
              git add "$conflicted_file"
          done
          # Commit the merge
          git commit -m "Merge branch main into customerX
          git push origin customerX
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}