name: Automate Merges to Customer X Branch

on:
  pull_request:
    branches:
      - customerX
  push:
    branches:
      - main

jobs:
  merge_customerX:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge requests from main
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          git fetch origin customerX
          git branch -la
          git checkout customerX
          git merge main --no-edit
          git push origin customerX
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}